### ISSUE TITLE
[BUG]: When changing time to notify in the tag the color of the tag change to red.

### ISSUE THREAD

**Issue by Jakarin-Jojo** [GarnBarn/garnbarn-frontend#48] opened 2021-11-25 12:23 UTC
## Step To Reproduce the bug:

1. Go to the home page and log in.
2. Click on the assignment.
3. Click on the tag of the assignment.
4. Click on the edit button.
5. Click on Notification Settings.
6. Change time to notice before the due date.
7. Click on save.
9. Repeat steps 4-8.
10. The color of the tag will change to red.

## Expected behavior

The color of the tag should be the color that is already set.

## Screenshots

![image](https://user-images.githubusercontent.com/72879083/143440868-3265b905-5afc-4ba4-abb3-77cf90f871d8.png)

**Comment by sirateek** [comment] 2021-11-25 13:47
I can definitely reproduce this bug now. This seems to be the problem with the color-picking tools we use (Similar to #46). 

Anyway, Thank you for reporting this to me. This will be fixed along with the #46

**Comment by sirateek** [comment] 2021-11-27 14:09
This has been fixed in #49 and has been deployed to the production environment. Thank you again for reporting this to us.

**Closed** 2021-11-27 14:09 UTC
Labels: bug
